# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eeed1022decd7e090c3f37e65fbb2a644c7e88a9d9799b6b0b4a570eb448c12957e74e490cbc9daae63563dc688cd717f899af095e3f76168d1787d4b80d4502

test:
  secret_key_base: c679b88b43100e326c326f9d7cd8d47278acfe2b6fed54c7ec2f57179b942a8346e09af5ecc3a2997b0c400e55bdc9e4455706543b5bcaa82a54ef39754856e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
